var province = [
    { "ProID": 1, "ProName": "安徽", "ProSort": 1, "ProRemark": "直辖市" },
    { "ProID": 2, "ProName": "江苏", "ProSort": 2, "ProRemark": "直辖市" },
    { "ProID": 3, "ProName": "上海", "ProSort": 6, "ProRemark": "省份" },
    { "ProID": 4, "ProName": "浙江", "ProSort": 5, "ProRemark": "省份" }

];
var city = [
    { "CityID": 1, "CityName": "合肥", "ProID": 1, "CitySort": 1 }, 
    { "CityID": 2, "CityName": "蚌埠", "ProID": 1, "CitySort": 2 },
    { "CityID": 3, "CityName": "阜阳", "ProID": 1, "CitySort": 3 },
    { "CityID": 4, "CityName": "六安", "ProID": 1, "CitySort": 4 },
    { "CityID": 5, "CityName": "马鞍山", "ProID": 1, "CitySort": 5 },
    { "CityID": 6, "CityName": "铜陵", "ProID": 1, "CitySort": 6 },
    { "CityID": 7, "CityName": "芜湖", "ProID": 1, "CitySort": 7 }, 
    { "CityID": 8, "CityName": "淮北", "ProID": 1, "CitySort": 8 }, 
    { "CityID": 9, "CityName": "淮南", "ProID": 1, "CitySort": 9 },
    { "CityID": 10, "CityName": "毫州", "ProID": 1, "CitySort": 10 },

    { "CityID": 11, "CityName": "常州", "ProID": 2, "CitySort": 1 },
    { "CityID": 12, "CityName": "丹阳", "ProID": 2, "CitySort": 2 },
    { "CityID": 13, "CityName": "淮安", "ProID": 2, "CitySort": 3 },
    { "CityID": 14, "CityName": "江阴", "ProID": 2, "CitySort": 4 },
    { "CityID": 15, "CityName": "靖江", "ProID": 2, "CitySort": 5 },
    { "CityID": 16, "CityName": "昆山", "ProID": 2, "CitySort": 6 },
    { "CityID": 17, "CityName": "连云港", "ProID": 2, "CitySort": 7 },
    { "CityID": 18, "CityName": "南京", "ProID": 2, "CitySort": 8 },
    { "CityID": 19, "CityName": "南通", "ProID": 2, "CitySort": 9 },
    { "CityID": 20, "CityName": "镇江", "ProID": 2, "CitySort": 10 },
    { "CityID": 21, "CityName": "苏州", "ProID": 2, "CitySort": 10 },
    { "CityID": 22, "CityName": "苏州常熟", "ProID": 2, "CitySort": 1 },
    { "CityID": 23, "CityName": "太仓", "ProID": 2, "CitySort": 2 },
    { "CityID": 24, "CityName": "泰州", "ProID": 2, "CitySort": 3 },
    { "CityID": 25, "CityName": "无锡", "ProID": 2, "CitySort": 4 },
    { "CityID": 26, "CityName": "吴江", "ProID": 2, "CitySort": 5 },
    { "CityID": 27, "CityName": "宿迁", "ProID": 2, "CitySort": 6 },
    { "CityID": 28, "CityName": "徐州", "ProID": 2, "CitySort": 7 },
    { "CityID": 29, "CityName": "盐城", "ProID": 2, "CitySort": 8 },
    { "CityID": 30, "CityName": "扬州", "ProID": 2, "CitySort": 9 },
    { "CityID": 31, "CityName": "宜兴", "ProID": 2, "CitySort": 10 },
    { "CityID": 32, "CityName": "张家港", "ProID": 2, "CitySort": 10 },

    { "CityID": 33, "CityName": "上海", "ProID": 3, "CitySort": 10 },

    { "CityID": 34, "CityName": "东阳", "ProID": 4, "CitySort": 1 },
    { "CityID": 35, "CityName": "富阳", "ProID": 4, "CitySort": 2 },
    { "CityID": 36, "CityName": "杭州", "ProID": 4, "CitySort": 3 },
    { "CityID": 37, "CityName": "湖州", "ProID": 4, "CitySort": 4 },
    { "CityID": 38, "CityName": "嘉兴", "ProID": 4, "CitySort": 5 },
    { "CityID": 39, "CityName": "嘉兴海宁", "ProID": 4, "CitySort": 6 },
    { "CityID": 40, "CityName": "嘉兴桐乡", "ProID": 4, "CitySort": 7 },
    { "CityID": 41, "CityName": "金华", "ProID": 4, "CitySort": 8 },
    { "CityID": 42, "CityName": "丽水", "ProID": 4, "CitySort": 9 },
    { "CityID": 43, "CityName": "临海", "ProID": 4, "CitySort": 10 },
    { "CityID": 44, "CityName": "宁波", "ProID": 4, "CitySort": 10 },
    { "CityID": 45, "CityName": "宁波慈溪", "ProID": 4, "CitySort": 1 },
    { "CityID": 46, "CityName": "宁波余姚", "ProID": 4, "CitySort": 2 },
    { "CityID": 47, "CityName": "宁波周巷", "ProID": 4, "CitySort": 3 },
    { "CityID": 48, "CityName": "浦江", "ProID": 4, "CitySort": 4 },
    { "CityID": 49, "CityName": "衢州", "ProID": 4, "CitySort": 5 },
    { "CityID": 50, "CityName": "瑞安", "ProID": 4, "CitySort": 6 },
    { "CityID": 51, "CityName": "绍兴", "ProID": 4, "CitySort": 7 },
    { "CityID": 52, "CityName": "绍兴嵊州", "ProID": 4, "CitySort": 8 },
    { "CityID": 53, "CityName": "台州", "ProID": 4, "CitySort": 9 },
    { "CityID": 54, "CityName": "温州", "ProID": 4, "CitySort": 10 },
    { "CityID": 55, "CityName": "义乌", "ProID": 4, "CitySort": 10 },
    { "CityID": 56, "CityName": "永康", "ProID": 4, "CitySort": 10 },
    { "CityID": 57, "CityName": "长兴", "ProID": 4, "CitySort": 10 },
    { "CityID": 58, "CityName": "舟山", "ProID": 4, "CitySort": 10 },
    { "CityID": 59, "CityName": "诸暨", "ProID": 4, "CitySort": 10 },

    { "CityID": 60, "CityName": "启东", "ProID": 2, "CitySort": 11 },
];
var dealer=
       [{ "Id": 1,"DisName": "安徽之星汽车销售服务有限公司", "CityID": 1, "DisSort": null,"DisAddress":"安徽省合肥市北二环汴河路段国际汽车城4号","MM":"易晴","Tel":"(86) 0551-6439 7666","Email":"yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "蚌埠星辉汽车销售服务有限公司", "CityID": 2, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 3, "DisName": "阜阳伟久汽车销售服务有限公司", "CityID": 3, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 4, "DisName": "合肥利之星汽车服务有限公司", "CityID": 1, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 5, "DisName": "安徽鹏龙融富汽车销售服务有限公司", "CityID": 1, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 6, "DisName": "六安恒信之星汽车销售服务有限公司", "CityID": 4, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 7, "DisName": "马鞍山之星汽车销售服务有限公司", "CityID": 5, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 8, "DisName": "铜陵利星汽车销售服务有限公司", "CityID": 6, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 9, "DisName": "芜湖中星汽车销售服务有限公司", "CityID": 7, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 10, "DisName": "淮北万帮之星汽车销售服务有限公司", "CityID": 8, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 11, "DisName": "淮南之星汽车销售服务有限公司", "CityID": 9, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 12, "DisName": "亳州之星汽车有限公司", "CityID": 10, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },

        { "Id": 1, "DisName": "常熟中升之星汽车销售服务有限公司", "CityID": 22, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "常州之星汽车有限公司", "CityID": 11, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "常州外汽星豪汽车销售服务有限公司", "CityID": 11, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "常州万帮明都汽车有限公司", "CityID": 11, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "常州外汽永豪汽车销售服务有限公司", "CityID": 11, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "常州外汽东豪汽车销售服务有限公司", "CityID": 11, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "丹阳之星汽车零部件有限公司", "CityID": 12, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "淮安之星汽车销售服务有限公司", "CityID": 13, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "淮安之星汽车销售服务有限公司清河新区分公司", "CityID": 13, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "淮安万帮金星汽车销售有限公司", "CityID": 13, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "江阴利之星汽车维修服务有限公司", "CityID": 14, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "泰州之星汽车销售服务有限公司靖江分公司", "CityID": 15, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "昆山利星汽车服务有限公司", "CityID": 16, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "连云港之星汽车销售有限公司", "CityID": 17, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "江苏中驰汽车销售服务有限公司", "CityID": 18, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "南京利之星汽车销售服务有限公司", "CityID": 18, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "南京利之星汽车销售服务有限公司红山路分公司", "CityID": 18, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "南京宁星汽车维修服务有限公司雨花东路分公司", "CityID": 18, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "南京万帮新区汽车销售服务有限公司", "CityID": 18, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "南京中升之星汽车销售服务有限公司", "CityID": 18, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "南京中升之星河西城市展厅", "CityID": 18, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "南京江北之星汽车服务有限公司", "CityID": 18, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
                
        { "Id": 2, "DisName": "南通之星汽车维修服务有限公司", "CityID": 19, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "南通文峰伟恒汽车销售服务有限公司", "CityID": 19, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "南通和星汽车销售服务有限公司", "CityID": 19, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "苏州海星汽车销售服务有限公司", "CityID": 21, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "苏州海星高新汽车销售服务有限公司", "CityID": 21, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "苏州利星汽车服务有限公司", "CityID": 21, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "苏州利星汽车服务有限公司园区旺墩路分公司", "CityID": 21, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "苏州元星汽车服务有限公司", "CityID": 21, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "苏州鹏龙东昌汽车销售服务有限公司", "CityID": 21, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "太仓中升之星汽车销售服务有限公司", "CityID": 23, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "泰州之星汽车销售服务有限公司", "CityID": 24, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "泰州市海驰汽车销售服务有限公司", "CityID": 24, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "无锡中升汽车销售服务有限公司", "CityID": 25, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "无锡可达汽车销售服务有限公司", "CityID": 25, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "无锡德星汽车维修服务有限公司", "CityID": 25, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "无锡德星汽车维修服务有限公司河埒口分公司", "CityID": 25, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "无锡中升星辉汽车销售服务有限公司", "CityID": 25, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "吴江之星汽车销售服务有限公司", "CityID": 26, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "宿迁文峰伟恒汽车销售服务有限公司", "CityID": 27, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "徐州利星行汽车服务有限公司", "CityID": 28, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "徐州之星汽车有限公司", "CityID": 28, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "盐城之星汽车有限公司", "CityID": 29, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "扬州利之星汽车维修服务有限公司", "CityID": 30, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "扬州海星汽车销售服务有限公司", "CityID": 30, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "宜兴市鹏龙汽车销售服务有限公司", "CityID": 31, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "宜兴利星汽车销售服务有限公司", "CityID": 31, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "张家港海星汽车销售服务有限公司", "CityID": 32, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "镇江京之星汽车有限公司", "CityID": 20, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "盐城市鹏龙森风汽车有限公司", "CityID": 29, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "启东和星汽车销售服务有限公司", "CityID": 60, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },


        
        
        { "Id": 2, "DisName": "镇江京之星汽车有限公司润州分公司", "CityID": 20, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "上海宝利德汽车有限公司", "CityID": 33, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "上海东驰汽车有限公司", "CityID": 33, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "上海东驰汽车有限公司世纪大道分公司", "CityID": 33, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "上海东华之星汽车维修服务有限公司宝山分公司", "CityID": 33, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "上海冠松之星汽车销售服务有限公司", "CityID": 33, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "上海汇之星汽车维修服务有限公司", "CityID": 33, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "上海利之星汽车有限公司", "CityID": 33, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "上海利之星汽车有限公司闵行分公司", "CityID": 33, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "上海闵星汽车服务有限公司", "CityID": 33, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "上海闵星金桥分公司", "CityID": 33, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "上海利星汽车维修有限公司", "CityID": 33, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "上海利星汽车维修有限公司延安西路分公司", "CityID": 33, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "上海星瀚汽车维修服务有限公司", "CityID": 33, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "上海星瀚汽车维修服务有限公司-金沙江路分公司", "CityID": 33, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "上海越星汽车有限公司 ", "CityID": 33, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "上海中升之星汽车销售服务有限公司 ", "CityID": 33, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "上海中升之星汽车销售服务有限公司奉贤分公司 ", "CityID": 33, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },

        { "Id": 2, "DisName": "浙江利星汽车有限公司 ", "CityID": 34, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "浙江越星汽车有限公司 ", "CityID": 34, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "杭州之信汽车有限公司 ", "CityID": 35, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "杭州百得利之星汽车销售有限公司 ", "CityID": 36, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "杭州东星行汽车维修有限公司 ", "CityID": 36, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "杭州奕星汽车服务有限公司 ", "CityID": 36, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "浙江鹏龙之奔汽车销售有限公司 ", "CityID": 36, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "浙江星杭汽车有限公司 ", "CityID": 36, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "浙江华策汽车有限公司 ", "CityID": 36, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "浙江华策北控汽车有限公司 ", "CityID": 36, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "浙江之信汽车有限公司 ", "CityID": 36, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "湖州之星汽车有限公司 ", "CityID": 37, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "嘉兴宝利德汽车有限公司 ", "CityID": 38, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "嘉兴合信汽车销售服务有限公司 ", "CityID": 38, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "海宁利星汽车有限公司 ", "CityID": 39, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "桐乡利之星汽车销售服务有限公司 ", "CityID": 40, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "金华金之星汽车贸易有限公司 ", "CityID": 41, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "丽水市丽水之星汽车有限公司 ", "CityID": 42, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "临海欧龙汽车有限公司 ", "CityID": 43, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "宁波利星汽车服务有限公司 ", "CityID": 44, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "宁波宁兴新宇汽车销售服务有限公司 ", "CityID": 44, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "宁波和星汽车销售服务有限公司 ", "CityID": 44, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "宁波之星汽车维修服务有限公司 ", "CityID": 44, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "浙江慈吉之星汽车有限公司 ", "CityID": 45, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "浙江慈吉之星汽车有限公司余姚分公司 ", "CityID": 46, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "宁波利之星汽车服务有限公司 ", "CityID": 46, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "浙江慈吉之星汽车有限公司周巷分公司 ", "CityID": 47, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "浦江国邦新城汽车销售服务有限公司 ", "CityID": 48, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "衢州欧龙汽车有限公司 ", "CityID": 49, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "瑞安市红升汽车销售服务有限公司 ", "CityID": 50, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "绍兴之星汽车有限公司 ", "CityID": 51, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "嵊州宝利德汽车有限公司 ", "CityID": 52, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "台州德星汽车有限公司汽车城展厅 ", "CityID": 53, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "台州德星汽车有限公司 ", "CityID": 53, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "台州黄岩之星汽车销售服务有限公司  ", "CityID": 53, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "台州欧普汽车销售有限公司 ", "CityID": 53, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "台州之星汽车销售服务有限公司 ", "CityID": 53, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "温州华能汽车销售服务有限公司 ", "CityID": 54, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "温州之星汽车有限公司 ", "CityID": 54, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "温州华能达汽车销售服务有限公司 ", "CityID": 54, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "乐清华星汽车销售服务有限公司 ", "CityID": 54, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "义乌市国邦汽车销售服务有限公司 ", "CityID": 55, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "义乌欧龙汽车销售服务有限公司 ", "CityID": 55, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "义乌利星汽车有限公司 ", "CityID": 55, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "义乌欧龙汽车销售服务有限公司汽车城展厅 ", "CityID": 55, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "永康市国邦汽车销售有限公司 ", "CityID": 56, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "永康利之星汽车销售服务有限公司 ", "CityID": 56, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "长兴之星汽车有限公司 ", "CityID": 57, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "舟山利星汽车销售服务有限公司 ", "CityID": 58, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
        { "Id": 2, "DisName": "浙江宝利德汽车有限公司 ", "CityID": 59, "DisSort": null, "DisAddress": "安徽省合肥市北二环汴河路段国际汽车城4号", "MM": "易晴", "Tel": "(86) 0551-6439 7666", "Email": "yiqing@anhuistar-benz.com" },
    ];